require('vue').component('vuco-button', require('../lib/button/component'))
require('vue').component('vuco-menu', require('../lib/menu/component'))
require('vue').component('vuco-menu-item', require('../lib/menu-item/component'))
require('vue').component('vuco-dropdown-button', require('../lib/dropdown-button/component'))
require('vue').component('vuco-input', require('../lib/input/input/component'))
require('vue').component('vuco-textarea', require('../lib/input/textarea/component'))
require('vue').component('vuco-checkbox', require('../lib/input/checkbox/component'))
require('vue').component('vuco-select', require('../lib/input/select/component'))